In [3]:
import tensorflow as tf
# 创建图
a=tf.constant(3,tf.float32)
b=tf.constant(4,tf.float32)
c=tf.constant(5,tf.float32)
y=tf.add(a*b,c)
print(y)
# 创建会话
sess=tf.Session()
# 计算
print(sess.run(y))
sess.close()

Tensor("Add_2:0", shape=(), dtype=float32)
17.0


In [6]:
# Tensor概述
import tensorflow as tf
row=3.0
col=4.0
# 值为0，指定维度的张量
zero_tsr=tf.zeros([row,col])
# 值为1，指定维度的张量
ones_tsr=tf.ones([row,col])
# 指定填充数值2.0
filed_tsr=tf.fill([3,4],2.0)
# 已知常数张量
constant_tsr=tf.constant([1,2,3])
# 所有元素为0，与constant_tsr类型已知的张量
zeros_similar=tf.zeros_like(constant_tsr)
# 所有元素为1，与constant_tsr类型已知的张量
ones_similar=tf.ones_like(constant_tsr)
# 创建指定区间，等间距的张量
liner_tsr=tf.linspace(start=0.0,stop=2.0,num=3)
# 创建指定区间，间距的张量
# 该数字序列开始于 start 并且将以 delta 为增量扩展到不包括 limit 时的最大值结束，类似python的range函数。
integer_seq_str=tf.range(start=0,limit=5,delta=1)
# 创建均匀分布随机数的张量
randunif_tsr=tf.random_uniform([3,4],minval=0,maxval=2)
# 创建正态分布随机数的张量
# mean: 正态分布的均值，默认为0;
# stddev: 正态分布的标准差，默认为1.0;
# dtype: 输出的类型，默认为tf.float32;
# seed: 随机数种子，是一个整数，当设置之后，每次生成的随机数都一样; 
# 操作的名称;
randnorm_tsr=tf.random_normal([3,4],mean=0.0,stddev=1.0)
# 创建指定边界的正态分布张量
# 这是一个截断的产生正太分布的函数，就是说产生正太分布的值如果与均值的差值大于两倍的标准差，那就重新生成。
# 和一般的正太分布的产生随机数据比起来，这个函数产生的随机数与均值的差距不会超过两倍的标准差，但是一般的别的函数是可能的。
runcnorm_tsr=tf.truncated_normal([3,4],mean=0.0,stddev=1.0)

# 创建会话
sess=tf.Session()
# 计算
print("zero_tsr\n",sess.run(zero_tsr))
print("ones_tsr\n",sess.run(ones_tsr))
print("filed_tsr\n",sess.run(filed_tsr))
print("constant_tsr\n",sess.run(constant_tsr))
print("zeros_similar\n",sess.run(zeros_similar))
print("ones_similar\n",sess.run(ones_similar))
print("liner_tsr\n",sess.run(liner_tsr))
print("integer_seq_str\n",sess.run(integer_seq_str))
print("randunif_tsr\n",sess.run(randunif_tsr))
print("randnorm_tsr\n",sess.run(randnorm_tsr))
print("runcnorm_tsr\n",sess.run(runcnorm_tsr))
sess.close()

zero_tsr
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones_tsr
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
filed_tsr
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
constant_tsr
 [1 2 3]
zeros_similar
 [0 0 0]
ones_similar
 [1 1 1]
liner_tsr
 [0. 1. 2.]
integer_seq_str
 [0 1 2 3 4]
randunif_tsr
 [[1.4259689  0.37850404 0.84241104 0.5221157 ]
 [0.36498904 0.06476641 1.7287757  0.36150217]
 [0.96472526 0.12623    0.68332624 1.2501032 ]]
randnorm_tsr
 [[ 0.4377336  -1.4419373  -0.40701997 -1.1973467 ]
 [ 1.2521363   0.18835638  0.88597554  1.0891105 ]
 [-0.3281451   0.25674996 -1.894375   -2.043175  ]]
runcnorm_tsr
 [[ 0.6346457  -1.8268919   0.8246625  -0.43811774]
 [ 1.428973    0.98842525 -0.19038568  0.53833437]
 [ 0.56912357  0.24580796 -0.4616332  -1.9631107 ]]


In [9]:
# Variable，通过调整这些变量优化机器学习
# 应该使用tf.Variable()函数，通过输入一个张量，返回一个变量。变量声明后需要进行初始化才能使用
tensor=tf.zeros([1,2])
# 声明变量
m_var=tf.Variable(tensor)
init_op=tf.global_variables_initializer()
with tf.Session() as sess:
    print('tensor is',sess.run(tensor))
    # print('m_var first is',sess.run(m_var))
    sess.run(init_op)
    print('m_var second is',sess.run(m_var))

tensor is [[0. 0.]]
m_var second is [[0. 0.]]


In [13]:
# Placeholder
# 用于表示输入输出数据的格式，允许传入指定类型和形状的数据。占位符仅仅声明了数据位置
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
z=tf.add(x,y)
with tf.Session() as sess:
    # feed_dict的作用是给使用placeholder创建出来的tensor赋值
    print(sess.run([[z]],feed_dict={x:[1.0,2.0],y:[10.0,11.0]}))

[[array([11., 13.], dtype=float32)]]


# operation
operation是tensorFlow图中的节点，他的输入输出都是Tensor。它用于完成各种操作，包括运算操作、矩阵操作和神经网络构建操作等。主要操作如下表所示

|操作组|操作|
|-|-|
数学运算操作|Add、Sub、Mul、Div、Exp、Log、Greater、Less、Equal
数组运算操作|Concat、Slice、Split、Constant、Rank、Shape、Shuffle
矩阵运算操作|MatMul、MatrixInverse、MatrixDeterminant
神经网络构建操作|Softmax、Sigmoid、ReLU、Convolution2D、MaxPool
检查点操作|Save、Restore
队列和同步操作|Enqueue、Dequeue、MutexAcquire、MutexRelease
张量控制操作|Merge、Switch、Enter、Leave、NextIteration

# Queue
Queue主要包含入列(enqueue)和出列(dequeue)两个操作。enqueue操作返回计算图中的一个Operation节点，dequeue操作返回一个Tensor值，需要放在Session中运行才可以获取真正的数值

|顺序出列|FIFOQueue
|-|-|
随机顺序出列的队列|RandomShuffleQueue

In [15]:
import tensorflow as tf
# 声明顺序队列或随机顺序出列的队列
# q=tf.FIFOQueue(10,"float")
# 最大长度10,最小长度2,类型float的随机队列
q=tf.RandomShuffleQueue(capacity=10, min_after_dequeue=0, dtypes="float")
init=q.enqueue_many(([1.0,2.0,3.0,4.0,5.0,6.0],))
with tf.Session() as sess:
    sess.run(init)
    queue=sess.run(q.size())
    for i in range(queue):
        print('q',sess.run(q.dequeue()))

q 5.0
q 2.0
q 3.0
q 4.0
q 1.0
q 6.0


对于一个队列长度为10，出队后最小长度为2的队列，实现如下

In [4]:
import tensorflow as tf
# 声明顺序队列或随机顺序出列的队列
# q=tf.FIFOQueue(10,"float")
# 最大长度10,最小长度2,类型float的随机队列
q=tf.RandomShuffleQueue(capacity=10, min_after_dequeue=0, dtypes="float")
init=q.enqueue_many(([1.0,2.0,3.0,4.0,5.0,6.0],))
# 定义3s超时
run_options=tf.RunOptions(timeout_in_ms=10000)
with tf.Session() as sess:
    sess.run(init)
    queue=sess.run(q.size())
    for i in range(queue):
        try:
            print('q''''''',sess.run(q.dequeue(), options=run_options))
        except tf.errors.DeadlineExceededError:
            print("Timeout")

q 4.0
q 6.0
q 1.0
q 3.0
q 5.0
q 2.0


# QueueRunner
QueueRunner即队列管理器，包括CPU、GPU、内存以及读取数据时计算机使用的其他硬件资源。

创建QueueRunner需要使用方法tf.train.QueueRunner._init_(queue,enqueue_ops)。enqueue_ops表示指定操作，一般是多个操作，每个操作都是一个线程。

使用方法tf.train.QueueRunner.create_threads(sess,coord=None,daemon=False,start=False)来完成线程的创建

例如：创建一个队列管理器，进行两个操作。一个操作完成计数器的自增，另一个操作将计数器的值入队。

In [5]:
import tensorflow as tf
# 声明顺序队列或随机顺序出列的队列
q=tf.FIFOQueue(10,"float")
counter=tf.Variable(0.0)
# 给计数器+1
increment_op=tf.assign_add(counter,1.0)
# 将计数器加入队列
enqueue_op=q.enqueue(counter)
# 创建两个操作的进程，*1表示一个操作拥有一个线程
qr=tf.train.QueueRunner(q,enqueue_ops=[increment_op,enqueue_op]*1)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    qr.create_threads(sess,start=True)
    for i in range(8):
        print(sess.run(q.dequeue()))

W1111 22:04:22.075101 13096 deprecation.py:323] From <ipython-input-5-dc418428c5c6>:10: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
E1111 22:04:22.349248 11712 queue_runner_impl.py:275] Exception in QueueRunner: Enqueue operation was cancelled
	 [[{{node fifo_queue_enqueue}}]]
E1111 22:04:22.366203 12400 queue_runner_impl.py:275] Exception in QueueRunner: Run call was cancelled


0.0
6.0
15.0
22.0
32.0
45.0
53.0
60.0


# Coordinator
Coordinator处理线程间的同步

在线程创建时，指定一个协调器，当主线程完成操作后，使用Coordinator.request_stop()方法，通知所有线程停止当前线程，并等待其他线程结束后返回结果。具体实现如下：

In [6]:
import tensorflow as tf
# 声明顺序队列或随机顺序出列的队列
q=tf.FIFOQueue(10,"float")
counter=tf.Variable(0.0)
# 给计数器+1
increment_op=tf.assign_add(counter,1.0)
# 将计数器加入队列
enqueue_op=q.enqueue(counter)
coord=tf.train.Coordinator()
# 创建两个操作的进程，*1表示一个操作拥有一个线程
qr=tf.train.QueueRunner(q,enqueue_ops=[increment_op,enqueue_op]*1)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # 对进程指定协调器
    queue_thread=qr.create_threads(sess,coord=coord,start=True)
    for i in range(8):
        print(sess.run(q.dequeue()))
    # 通知线程关闭
    coord.request_stop()
    # 等待线程结束
    coord.join(queue_thread)


4.0
15.0
23.0
31.0
40.0
49.0
59.0
72.0
